app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('', views.principal_view, name='principal'), 
    path('principal/', views.principal_view, name='principal'), 
    path('inicio/', views.inicio_view, name='inicio'), 
    path('inicio_ciudadano/', views.inicio_ciudadano_view, name='inicio_ciudadano'), 
    path('inicio/cambiar_datos/', views.cambiar_datos_view, name='cambiar_datos_view'), 
    path('principal/iniciar_sesion/', views.iniciar_sesion_view, name='iniciar_sesion_view'), 
    path('principal/cerrar_sesion/', views.cerrar_sesion_view, name='cerrar_sesion_view'), 
    path('principal/iniciar_sesion_post/', views.form_iniciar_sesion_view, name='form_iniciar_sesion'), 
    path('principal/registro/', views.registro_view, name='registro_view'), 
    path('principal/registro_post/', views.form_registro_view, name='form_registro_view'), 
    path('inicio/crear_partido/', views.crear_partido_view, name='crear_partido_view'), 
    path('inicio/crear_partido_post/', views.form_crear_partido, name='form_crear_partido'), 
    path('inicio/crear_individuo/', views.crear_individuo_view, name='crear_individuo_view'), 
    path('inicio/crear_individuo_post/', views.form_crear_individuo_view, name='form_crear_individuo'), 
    path('inicio/crear_proceso/', views.crear_proceso_view, name='crear_proceso_view'),
    path('inicio/crear_proceso_form/', views.form_crear_proceso_view, name='form_crear_proceso'), 
    path('inicio/consultar_lista_partido/', views.consultar_lista_partido_view, name='consultar_lista_partido_view'),
    path('inicio/consultar_partido/', views.consultar_partido_view, name='consultar_partido_view'), 
    path('inicio/consultar_partido/consultar_partido_form', views.consultar_partido_form, name='consultar_partido_form'),
    path('inicio/consultar_lista/', views.consultar_lista_view, name='consultar_lista_view'),  
    path('inicio/consultar_lista_post/', views.consultar_lista_post, name='consultar_lista_post'),  
    path('inicio/consultar_individuos/', views.consultar_individuo_view, name='consultar_individuo_view'), 
    path('inicio/consultar_individuos/consultar_individuo_form', views.consultar_individuo_form, name='consultar_individuo_form'), 


    path('inicio/consultar_procesos/', views.consultar_proceso_view, name='consultar_proceso_view'),
    path('inicio/consultar_proceso/', views.consultar_proceso_individual_view, name='consultar_proceso_individual_view'),
    path('inicio/aprobar_individuo/', views.aprobar_individuo_view, name='aprobar_individuo_view'),
    path('inicio/aprobar_individuo_post/', views.aprobar_individuo_post, name='aprobar_individuo_post'),
    path('inicio/aprobar_afiliacion/', views.aprobar_afiliacion_view, name='aprobar_afiliacion_view'),
    path('inicio/aprobar_afiliacion_post/', views.aprobar_afiliacion_post, name='aprobar_afiliacion_post'),
    path('inicio/aprobar_proceso/', views.aprobar_proceso_view, name='aprobar_proceso_view'),
    path('inicio/aprobar_proceso_post/', views.aprobar_proceso_post, name='aprobar_proceso_post'),
    path('inicio/implicar_afiliado/', views.implicar_afiliado_view, name='implicar_afiliado_view'),
    path('inicio/implicar_afiliado_post/', views.implicar_afiliado_post, name='implicar_afiliado_post'),
    path('inicio/habilitar_ciudadano/', views.habilitar_ciudadano_view, name='habilitar_ciudadano_view'),
    path('inicio/habilitar_ciudadano_post/', views.habilitar_ciudadano_post, name='habilitar_ciudadano_post'),
    path('inicio/afiliar_individuo/', views.afiliar_individuo_view, name='afiliar_individuo_view'),
    path('principal/error/', views.error_registro_view, name='error_registro_view'),
    path('inicio/cambiar_datos_form/', views.cambiar_datos_form, name='cambiar_datos_form'),
    path('inicio/afiliar_individuo/afiliar_individuo_form', views.afiliar_individuo_form, name='afiliar_individuo_form'),
]

proyecto_corrupcion/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/html/ConsultarProceso.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/consultarIndividuo.css' %}" />
    <title>Consultar Proceso</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          id="imageIcon"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
        <br>
      <h1 id="titleProcess">{{ proceso.titulo }}</h1><br>
      <span id="views">Cantidad de visitas : {{ proceso.vistas }} </span><i class="fas fa-eye"></i><br /><br>
      <p id="dateStart">Fecha de inicio : {{ proceso.fecha_inicio }}</p><br>
      <table id="procesos">
        <thead>
          <tr>
            <caption id="titleTable">
              Procesos
            </caption>
          </tr>
          <tr>
            <th>Estado</th>
            <th>Entidad</th>
            <th>Monto</th>
            <th>Comentarios del proceso</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {% if proceso.abierto %}
              <td class="estado">Abierto</td>
            {% else %}
            <td class="estado">Cerrado</td>
            {% endif %}
            <td class="entidad">{{ proceso.entidad }}</td>
            <td class="monto">{{ proceso.monto }}</td>
            <td class="cproceso">{{ proceso.comentarios }}</td>
          </tr>
        </tbody>

      </table>
      <br /><br />
      <table id="implicados">
        <thead>
          <tr>
            <caption id="titleTable">
              Lista de implicados
            </caption>
          </tr>
          <tr>
            <th>Nombre</th>
            <th>Partido politico actual</th>
            <th>Fecha de acusación</th>
            <th>acusación</th>
            <th>Veredicto</th>
            <th>Pena</th>
            <th>Comentarios implicación</th>
          </tr>
        </thead>
        <tbody>
            {% for implicado in implicados %}
            <tr></tr>
                <td class="Nombres">{{ implicado.id_afiliado.id_individuo.nombres }} {{ implicado.id_afiliado.id_individuo.apellidos }}</td>
                <td class="partido">{{ implicado.id_afiliado.id_partido.nombre }}</td>
                <td class="fechaacusacion">{{ implicado.fecha }}</td>
                <td class="acusacion">{{ implicado.acusacion }}</td>
                {% if proceso.abierto %}
                  <td class="declarado">Culpable</td>
                {% else %}
                  <td class="declarado">Inocente</td>
                {% endif %}
                <td class="pena">{{ implicado.pena }}</td>
                <td class="cimplicacion">{{ implicado.comentarios }}</td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
      <br>
      <button class="botones" id="return" onclick="location.href=`{% url 'app:consultar_proceso_view' %}`">Regresar</button>
  </div>

  </body>
</html>

app/templates/app/html/afiliar_individuo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'app/css/aprobar_individuo.css' %}"/>
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <title>Afiliar individuo</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          id="imageIcon"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
      <form action="afiliar_individuo_form" method="post">
        {% csrf_token %}
        <fieldset>
          <h1>Id Individuo <span>*</span></h1>
          <br />
          <select name="selec_ind">
            {% for i in ruta %}
            <option value="{{i.id}}">{{i.nombres}} {{i.apellidos}}</option>
            {% endfor %}
          </select>
          <h1>Id Partido<span>*</span></h1>
          <br />
          <select name="selec_part">
            <!-- {% for i in rutap %} -->
            <option value="{{i.id}}">{{i.nombre}}</option>
            <!-- {% endfor %} -->
          </select>
          <h1>Fecha de ingreso<span></span></h1>
          <br />
          <input type="date" name="startDate" />
          <br />
          <h1>Fecha de salida<span></span></h1>
          <input type="date" name="endDate"/><br />
          <button type="submit" class="botones" id="aceptar"
          onclick="location.href='{% url 'app:afiliar_individuo_view' %}'">
          Aceptar
          </button>

        </fieldset>


      </form>

      <br />

      <!-- <button
       class="botones"
        id="aceptar"
        onclick="location.href='{% url 'app:afiliar_individuo_view' %}'">
        Aceptar
      </button> -->
      <button
        class="botones"
        id="aceptar"
        onclick="location.href='{% url 'app:inicio' %}'">
        Regresar
      </button>

    </div>
  </body>
</html>

app/templates/app/html/aprobarAfiliación.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="../css/header.css" />
    <link rel="stylesheet" href="../css/aprobarProceso.css" /> -->

    <link
      rel="stylesheet"
      href="{% static 'app/css/consultar_lista_partido.css' %}"
    />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/implicarAfiliado.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/inicio.css' %}" />

    <title>Aprobar afiliación</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          id="imageIcon"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
      <form action="{% url 'app:aprobar_afiliacion_post' %}" method="post">
        {% csrf_token %}
        <fieldset>
          <h1>Individuo <span>*</span></h1>
          <br />
          <select name="seleccionar_ind">
            {% for i in holi %}
            <option value="{{i.id}}">
              {{i.id_individuo.nombres}} {{i.id_individuo.apellidos}}. Afiliado
              a: {{i.id_partido.nombre}}
            </option>
            {% endfor %}
          </select>
          <br />
          <br />
          <h1>Aprobación<span>*</span></h1>
          <br />
          <select name="seleccionar">
            <option value="10">Aprobado</option>
            <option value="11">Desaprobado</option></select
          ><br /><br />
        </fieldset>
        <button class="botones" id="aceptar">Aceptar</button><br />
      </form>

      <button
        class="botones"
        id="aceptar"
        onclick="location.href='{% url 'app:inicio' %}'"
      >
        Regresar
      </button>
      <br />
    </div>
  </body>
</html>

app/templates/app/html/consultar_partidoprev.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/aprobar_individuo.css' %}" />

    <title>Consultar partido</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img src="{% static 'app/img/inicio.png' %}" id="imageIcon" onclick="location.href='{% url 'app:inicio' %}'"/>
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
      <h1>Partido <span>*</span></h1>
      <br />
      <select>
        <option value="1">Partido 1</option>
        <option value="2">Proceso 2</option>
        <option value="3">Proceso 3</option>
       </select
      ><br />

      <button class="botones" id="aceptar" onclick="location.href='{% url 'app:consultar_partido_view' %}'">
        Confirmar</button
      ><br />
      <button
        class="botones"
        id="aceptar"
        onclick="location.href='{% url 'app:inicio' %}'">
        Regresar</button
      ><br />
    </div>
  </body>
</html>

app/templates/app/html/consultarprocesoprev.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/aprobar_individuo.css' %}" />
    <title>Consultar individuo</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          id="imageIcon"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
      <form action="{% url 'app:consultar_proceso_individual_view' %}" method="post">
        {% csrf_token %}
        <h1>Proceso <span>*</span></h1>
        <br />
        <select name="id">
          {% for proceso in procesos %}
            <option value="{{ proceso.id }}">{{ proceso.titulo }}</option>
          {% endfor %}
         </select
        ><br />
        <button class="botones" id="aceptar">
          Confirmar</button
        ><br />
      </form>
      <button class="botones" id="cancelar" onclick="location.href=`{% url 'app:inicio' %}`">Cancelar</button>
    </div>
  </body>
</html>

app/templates/app/html/crear_individuo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear individuo</title>
    <link rel="stylesheet" href="{% static 'app/css/crear_individuo.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
</head>
<body>
    <div id="HeaderBody">
        <div id="Icon">
          <img
            src="{% static 'app/img/inicio.png' %}"
            id="imageIcon"
            onclick="location.href='{% url 'app:inicio' %}'"
          />
        </div>
        <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
        <div id="botonContainer">
          <button
            id="uptade"
            class="botones"
            onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
          >
            Mi cuenta
          </button>
          <button
            id="LogOut"
            class="botones"
            onclick="location.href='{% url 'app:principal' %}'"
          >
            Cerrar Sesión
          </button>
        </div>
      </div>
    <div class="menu">
        <div class="parrafo">
            <p id="usuario">
                Nombre *
            </p>
            <form action="{% url 'app:form_crear_individuo' %}" method="post">
                {% csrf_token %}
                <input id="user" type="text" name="usuario" placeholder="Nombre">
                <p id="apellido">
                Apellido *
                </p>
                <input id="lastname" type="text" name="Apellido" placeholder="Apellido">
                <p id="fecha">
                Fecha de nacimiento
                </p>
                <input id="date" type="date" name="date" >
                <button class="botonesf1" id="consultar">Crear individuo</button>
            </form> 
    </div>
    
    <button class="botonesf2" id="cancelar" onclick="location.href=`{% url 'app:inicio' %}`">Cancelar</button>

</body>
</html>

app/templates/app/html/crear_partido.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Crear Partido político</title>
    <link rel="stylesheet" href="{% static 'app/css/crear_partido.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          id="imageIcon"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
      <br />
      <p id="nombre">Nombre <span>*</span></p>
      <form action="{% url 'app:form_crear_partido' %}" method="post">
        {% csrf_token %}
        <input id="user" type="text" name="nombre" placeholder="Nombre" />
        <button class="botones" id="aceptar" onclick="location.href='#'">
        Confirmar</button
       ><br />
       </form>
      <button
        class="botones"
        id="aceptar"
        onclick="location.href=`{% url 'app:inicio' %}`"
      >
        Regresar</button
      ><br />
    </div>
  </body>
</html>

app/templates/app/html/habilitar_ciudadano.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'app/css/aprobar_individuo.css' %}"/>
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <title>Habilitar/Deshabilitar</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          alt="corrupcion"
          id="imgcorrupcion"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
    <div id="content">
      <form action="{% url 'app:habilitar_ciudadano_post' %}" method="post">
        {% csrf_token %}
        <fieldset>
          <h1>Individuo <span>*</span></h1>
          <br />
          <select name="seleccionar_ind">
            {% for i in ruta %}
            <option value="{{i.id}}">{{i.first_name}} {{i.last_name}}</option>
            {% endfor %}
          </select>
          <br />
          <br />
          <h1>Habilitar/Deshabilitar<span>*</span></h1>
          <br />
          <select name="seleccionar">
            <option value="10">Habilitar</option>

            <option value="11">Deshabilitar</option></select
          ><br />
        </fieldset>
        <button
        class="botones"
        id="aceptar"
      >
        Aceptar
      </button>
      </form>
      <br />
      <button
        class="botones"
        id="aceptar"
        onclick="location.href='{% url 'app:inicio' %}'"
      >
        Regresar
      </button>
    </div>
  </body>
</html>

app/templates/app/html/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'app/css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/implicarAfiliado.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/inicio.css' %}" />

    <title>Inicio</title>
  </head>
  <body>
    <div id="HeaderBody">
      <div id="Icon">
        <img
          src="{% static 'app/img/inicio.png' %}"
          id="imageIcon"
          onclick="location.href='{% url 'app:inicio' %}'"
        />
      </div>
      <div id="title"><h1 id="texto">#NoMasCorrupcion</h1></div>
      <div id="botonContainer">
        <button
          id="uptade"
          class="botones"
          onclick="location.href='{% url 'app:cambiar_datos_view' %}'"
        >
          Mi cuenta
        </button>
        <button
          id="LogOut"
          class="botones"
          onclick="location.href='{% url 'app:principal' %}'"
        >
          Cerrar Sesión
        </button>
      </div>
      <div id="menudes">
        <ul class="nav">
          <li>
            <a href="#">CREACIÓN</a>
            <ul>
              <li>
                <a href="{% url 'app:crear_partido_view' %}"
                  >Crear partido político</a
                >
              </li>
              <li>
                <a href="{% url 'app:crear_individuo_view' %}"
                  >Crear individuo</a
                >
              </li>
              <li>
                <a href="{% url 'app:crear_proceso_view' %}">Crear proceso</a>
              </li>
            </ul>
          </li>

          <li>
            <a href="#">CONSULTAS</a>
            <ul>
              <li>
                <a href="{% url 'app:consultar_lista_partido_view' %}"
                  >Consultar lista de partidos políticos</a
                >
              </li>
              <li>
                <a href="{% url 'app:consultar_partido_view' %}"
                  >Consultar partido político</a
                >
              </li>
              <li>
                <a href="{% url 'app:consultar_lista_view' %}"
                  >Consultar lista de individuos
                </a>
              </li>
              <li>
                <a href="{% url 'app:consultar_individuo_view' %}"
                  >Consultar individuo</a
                >
              </li>
              <li>
                <a href="{% url 'app:consultar_proceso_view' %}"
                  >Consultar proceso</a
                >
              </li>
            </ul>
          </li>
          <li>
            <a href="#">APROBACION</a>
            <ul>
              <li>
                <a href="{% url 'app:aprobar_individuo_view' %}"
                  >Aprobar individuo</a
                >
              </li>
              <li>
                <a href="{% url 'app:aprobar_afiliacion_view' %}"
                  >Aprobar afiliación</a
                >
              </li>
              <li>
                <a href="{% url 'app:aprobar_proceso_view' %}"
                  >Aprobar proceso</a
                >
              </li>
            </ul>
          </li>
          <li>
            <a href="#">OTROS</a>
            <ul>
              <li>
                <a href="{% url 'app:implicar_afiliado_view' %}"
                  >Implicar un afiliado en un proceso</a
                >
              </li>
              <li>
                <a href="{% url 'app:habilitar_ciudadano_view' %}"
                  >Habilitar/Deshabilitar ciudadano</a
                >
              </li>
              <li>
                <a href="{% url 'app:afiliar_individuo_view' %}"
                  >Afiliar individuo a partido</a
                >
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <div id="content">
      <table id="inicioCiudadano">
        <thead>
          <tr>
            <caption id="titleTable">
              Partidos Politicos
            </caption>
          </tr>
          <tr>
            <th>Foto</th>
            <th>Nombre</th>
            <th>Vistas</th>
          </tr>
        </thead>
        <tbody>
          {% for cat in listapartido %}
          <tr>
            <td class="Logos">
              <img
              src="{% static 'app/img/liberal.png' %}"
              class="imgPartidos"
              onclick="location.href='{% url 'app:consultar_partido_view' %}'"
            />
            </td>
	          <td class="Nombre">{{ cat.nombre }}</td>
            <td class="Visitas">{{ cat.vistas }}</td>
          </tr> 
          {% endfor %}

        </tbody>
      </table>
    </div>
  </body>
</html>